### ISSUE TITLE
Extend section: high level design

### ISSUE THREAD

**Issue by ccbrown** [mattermost/mattermost-developer-documentation#1]
High level design. Individual issues can be opened for each section. 

- [ ] Plugins
    - [x] Overview
    - [x] The Manifest (with reference / documentation parsed from source)
    - [x] Front-end
        - [x] Introduction - How front-end customization is done, broad overview.
        - [x] Quickstart - Hello world!
        - [x] API Reference - Which elements can be plugged into, etc.
        - [ ] Playground? - Seems like it would be feasible to create a playground environment for UI elements.
    - [x] Back-end
        - [x] Introduction - How back-end customization is done, broad overview.
        - [x] Quickstart - Hello world!
        - [x] API Reference - More or less [the godoc page](https://godoc.org/github.com/mattermost/mattermost-server/plugin), reskinned.
    - [ ] Examples
- [ ] Forking Mattermost

**Comment by jwilander** [comment]
I think having separate sections for frontend/backend makes a lot of sense but I'd like to somehow emphasize the fact that a single plugin can contain both the frontend and backend. Essentially you'd have a single Jira plugin that has both frontend and backend parts, instead of two separate frontend and backend Jira plugins

0/5 on how that's done but it's something I think is important for how developers think about plugins as a whole

**Comment by ccbrown** [comment]
@jwilander True. I've been using the terms "front-end plugin" and "back-end plugin" like they're two separate things, but I should probably avoid using those terms. How about a top level plugin section with a plugin overview and a single examples section? (See updated above.)

**Comment by jwilander** [comment]
Yeah, that looks great 👍

**Comment by jwilander** [comment]
Going to write some front-end plugin documentation

**Comment by ccbrown** [comment]
Forgot something important: Manifest schema.

**Comment by ccbrown** [comment]
I think if we add an "examples" page that showcases the JIRA / Zoom plugins, we'll be ready to close this issue. I'll probably create that tomorrow.
