### ISSUE TITLE
HTTP Code Visible in Developer Setup Documentation

### ISSUE THREAD

**Issue by shadowshot-x** [mattermost/mattermost-developer-documentation#1193]
#### Summary
Seeing unintentional links and HTTP/Template code in Mattermost documentation page for Developer Setup. https://developers.mattermost.com/contribute/more-info/server/developer-setup/ 

#### Steps to reproduce
Browse to https://developers.mattermost.com/contribute/more-info/server/developer-setup/ 

#### Expected behavior
Title should be visible as hyperlink text.

#### Observed behavior (that appears unintentional) 
Title, link and code visible.

#### Possible fixes
I am guessing the template is not parsing correctly due to minor issue/typo.

Proof :- 
<img width="760" alt="Screenshot 2023-01-02 at 1 32 35 PM" src="https://user-images.githubusercontent.com/43992469/210206701-e3212e98-b787-4a9f-9f9b-83fde7e4584a.png">
<img width="774" alt="Screenshot 2023-01-02 at 1 32 46 PM" src="https://user-images.githubusercontent.com/43992469/210206706-e26e8bab-b892-4d4c-bbd2-a3f16a4a9eb7.png">
<img width="743" alt="Screenshot 2023-01-02 at 1 32 56 PM" src="https://user-images.githubusercontent.com/43992469/210206707-01777191-ae38-4d69-a403-60432b901f19.png">

PS. I am using Google Chrome Version 108.0.5359.124 (Official Build) (arm64)

**Comment by cwarnermm** [comment]
Thanks for raising this issue, @shadowshot-x! In the production environment, I'm seeing this issue resolved:
![image](https://user-images.githubusercontent.com/74422101/213201238-c47decf2-8756-4f0f-a478-6afc2b4af4d2.png)

I'm running Edge v109.0.1518.52 (Official build) (arm64). Can you confirm that you're continuing to see this issue? And if you are, please indicate which browsers you're using where you see the issue. If the issue is browser-based, this information will be very helpful. Thanks!
