### ISSUE TITLE
Request for Documentation: Docker bridge network can interfere with the Mattermost VPN and DNS resolution for  internal.mattermost.com (172.18.0.0/16)

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-developer-documentation#459]
Mattermost user `jason.deland` from https://community.mattermost.com has requested the following be documented:

```
Just an FYI - you can also use docker cli
jpd@pop-os:~/go/src/github.com/mattermost/mattermost-server$ docker network rm mattermost-server_mm-test
mattermost-server_mm-test

```

See the original post [here](https://community.mattermost.com/_redirect/pl/cfo4ud7dyf8cif7hdzc3pwbw1r).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by RohitJain13** [comment]
The original post referenced cannot be found

**Comment by jaydeland** [comment]
@rohitjain13 First off - thank you for taking an interest in this issue and helping us get it resolved 😊!

It was a private conversation between myself and Daniel S. Basically, the docker-compose network that is created when you use our makefile defaults to 172.18.0.0/16

Just an FYI - you can also use docker cli
jpd@pop-os:~/go/src/github.com/mattermost/mattermost-server$ docker network rm mattermost-server_mm-test
mattermost-server_mm-test

We can also setup the docker bridge to use a different ip

Here are details on how to change the default:
https://success.docker.com/article/how-do-i-configure-the-default-bridge-docker0-network-for-docker-engine-to-a-different-subnet

**Comment by RohitJain13** [comment]
Should I enhance the documentation at https://docs.mattermost.com/install/prod-docker.html?highlight=compose to mention perhaps in step 3 that the network would default to 172.18.0.0/16 and if you want to change the default, see the reference you mention above?

And I could suggest there that you could use the docker cli instead of docker-compose.  I assume that the cli method is not documented in the manual anywhere that I can just link to, and therefore we would need to provide the steps for the cli as an alternative to the steps documented in step 3 for docker-compose.  But it is not clear to me that just entering the command as you have written it above would do it.  It does have jpd@pop-os in it :-).  What would those steps look like with the docker cli as different from the steps for docker-compose?

**Comment by jaydeland** [comment]
Hey @RohitJain13 - sorry for the confusion, the command above was used to remove the docker-compose network after changing the default config so that on the next run it will be generated again with the new default cidr.

**Comment by RohitJain13** [comment]
Okay, I understand now.  But could you spell out for me exactly what part of that is the command?  Is it just "docker network rm mattermost-server_mm-test"

**Comment by RohitJain13** [comment]
Please review pull request: https://github.com/mattermost/docs/pull/3480
Documenting how to change the default docker-compose network #3480
