### ISSUE TITLE
Style issues at Extend > Server Plugins > Reference

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-developer-documentation#50]
1) What is the note at the top?
2) Should "API" heading size match "Testing"? Feels a little large. 

![image](https://user-images.githubusercontent.com/13119842/33384253-7fb7b642-d4f3-11e7-99f6-8fa4000fe71f.png)

3) Same with heading size of the individual "API" heading sizes. We can probably just match the sizes from Web App Plugins > Reference
![image](https://user-images.githubusercontent.com/13119842/33384295-9d9cc4ea-d4f3-11e7-8b05-a985155c4dd5.png)

**Comment by jwilander** [comment]
1. Go documentation is generated automatically for all Go packages and it's a common place that most devs will go to look at documentation. I like having it there as a dev because 1) if I just want to go read the documentation in a format I'm familiar with I can just click that, and 2) I immediately know this is documentation for a Go package

2/3. I'll make some modifications to get more consistent heading sizes

**Comment by jasonblais** [comment]
1. I'm okay with the change in #53. I think I was confused because it seemed like the title of the page. 0/5 on whether it should be a heading or not

**Comment by ccbrown** [comment]
In addition to what Joram said, I also thought it was important to make it immediately clear to the user what they were looking at because the page is full of GoDoc links for everything (e.g. clicking on any type name takes you to the GoDoc page for it). Didn't want that to be too surprising. It should feel perfectly familiar to Go developers though.
