### ISSUE TITLE
Help Wanted: Check generated HTML file

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-developer-documentation#511]
To ensure the generated HTML files are valid and all links are working, a new step should be included in the CircleCI pipeline. Using https://github.com/gjtorikian/html-proofer or a similar proofer all generated files should be checked.

To reduce the initial work load to implement this changes, skipping some checks with e.g. `--empty_alt_ignore` is fine.

Bonus points for adding a `make check` target or including even more checks like `--check_html`.

**Comment by akshitarora921** [comment]
Hi, can I work on this?

**Comment by akshitarora921** [comment]
@hanzei Can you give me a heads-up? I don't know about it but It sounds interesting.

**Comment by cwarnermm** [comment]
@cpanato - Is this something your team can assist with?

**Comment by hanzei** [comment]
@cwarnermm What is the reasoning behind removing the Help Wanted from this issue? Can we keep this up for the community?

**Comment by cwarnermm** [comment]
@hanzei - The original ask was to add a step to the CircleCI pipeline. It's my understanding that we're migrating from CircleCI to GitHub actions. With this in mind, I looped Carlos in. I wasn't sure if this ticket would need some updates to take our updated infrastructure into account, or if Carlos' team would be needed for final execution.

@cpanato has confirmed that the same type of implementation would be possible via GitHub Actions. Since the ask is the same, I'm quite open to keeping this as a Help Wanted ticket open to our community, and will re-add the appropriate labels.

**Comment by varunKT001** [comment]
@cwarnermm Can I work on this?

**Comment by hanzei** [comment]
That would be awesome, thanks @varunKT001 :+1:
