### ISSUE TITLE
Apps docker development environment should be mentioned in the Apps dev docs

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-developer-documentation#942]
Link to the development environment README: https://github.com/mattermost/mattermost-plugin-apps/tree/master/dev

**Comment by justinegeffen** [comment]
@mickmister, can you confirm whether the current README is correct or if it still needs to be updated? If it does need an update, could you provide some source material? Thank you!

**Comment by mickmister** [comment]
@justinegeffen Sorry the ticket description is little vague, and seems to imply that the linked `README` should be updated. This ticket is in the https://github.com/mattermost/mattermost-developer-documentation repo because the change needs to be applied here. The linked `README` in the description is to a page in the Apps plugin repo. I'm suggesting we link to this page, in the Apps developer docs that lives in the dev docs repo.

The change can just be
"See the Apps [development environment guide](https://github.com/mattermost/mattermost-plugin-apps/tree/master/dev) to get set up!

I've also added some improvements to the README here https://github.com/mattermost/mattermost-plugin-apps/pull/301

**Comment by mickmister** [comment]
Hi @justinegeffen, just following up on this. Was there a link added in the Apps dev docs for the docker dev environment?

**Comment by justinegeffen** [comment]
Thanks, @mickmister! I closed this inadvertently when closing some others - do you have an idea of where you want this update to be? The Apps landing page, the [deployment page](https://developers.mattermost.com/integrate/apps/deploy/)? Happy to add it but not sure where you were thinking. :)

**Comment by azigler** [comment]
@justinegeffen @mickmister I can handle this one, because we'll ultimately need a little more than just linking and it'll necessitate brushing up a few of the pages. I'm working on restructuring these guides so that using this dev environment is more clear. This is related to [this ticket](https://mattermost.atlassian.net/browse/MM-39146?atlOrigin=eyJpIjoiYmMyODU4NmU2MDg1NDQ4MDkxMzZjNGM1NDg5ZDI5NTYiLCJwIjoiaiJ9) that'd assigned to me, so I went ahead and assigned this issue to myself and will link a PR when my updates are done.

**Comment by mickmister** [comment]
@azigler Sounds good to me :+1: Thanks for digging into the whole development process!

**Comment by justinegeffen** [comment]
Awesome, thanks @azigler, that makes a lot of sense. Appreciate it! :)
