### ISSUE TITLE
Request for Documentation: Apps landing page improvements

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-developer-documentation#950]
The [landing page](https://developers.mattermost.com/integrate/apps) for Apps documentation could be improved in two ways:
- Consistency between:
    - "app" versus "App" - I believe we converged on "App" being the public-facing wording
    - "apps framework" versus "Apps Framework" "App framework". - I think we converged on "App Framework" for public-facing wording. [0/5](https://handbook.mattermost.com/company/about-mattermost/list-of-terms#0-5-1-5-2-5-3-5-4-5-5-5) on what it should be, it should just be consistent.
- The blurriness of each image on the page is meant to showcase a given feature, by making the whole image blurry except for the focal point of the picture. It's not immediately clear what is being showcased. I think zooming in on the feature would be better than making the images blurry.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/btbjei3i17nu5b6z9qzxt3t1tw) *by @mickmister*._

**Comment by haardikdharma10** [comment]
This should be a quick fix. 

1. Replacing all instances of "app" with "App".
2. Should it be "App framework" or "Apps Framework" @mickmister? Where can we discuss on it though? 
3. Totally agree. For example, in "Add buttons to channel headers and post menus" section, it is very hard to figure out whether the focus is on the server named as "Marketing" or on the blue logo towards the left of search bar or both? This should indeed be changed by zooming in on the exact feature while still keeping the images blurry.

If any first-time contributor wants to take this up, please let us know by commenting on this issue, otherwise I'll fix this by tonight.

**Comment by hanzei** [comment]
When @justinegeffen and I talked about the terminology for the docs, the decision was to use `app`, not `App` as it's not a proper name. On the other hand , `App Framework` is a Mattermost specific thing.

**Comment by justinegeffen** [comment]
^^ What @hanzei said. :) 

An app is a universal term/thing so capitalizing it causes confusion. Even if it's "Mattermost App" we're still referring to the concept of an app and not an app specific to Mattermost. If it was specific it would be the "Mattermost something app". 

I do think there may be some inconsistency in the docs which I am happy to address.

**Comment by haardikdharma10** [comment]
Great discussion everyone! @jfrerich, I have added the zoomed-in feature images here - https://github.com/mattermost/mattermost-developer-documentation/pull/954 🙂
